os: linux
dist: trusty
sudo: required
language: python

services:
  - docker

install:
  - docker-compose -f docker-compose.test.yml build

script:
  - docker-compose -f docker-compose.test.yml run --rm cheddar py.test
